import { Converter } from 'opencc-js';

export const botLanguages = ['zh-Hant', 'zh-Hans', 'en', 'ja', 'ko', 'es', 'fr', 'ru'] as const;
export type BotLanguage = typeof botLanguages[number];
export function telegramLanguage(code?: string): BotLanguage {
  const tag = (code || '').trim().replaceAll('_', '-').toLowerCase();
  if (/^zh(?:-|$)/.test(tag)) {
    if (/(?:^|-)hant(?:-|$)/.test(tag)) return 'zh-Hant';
    if (/(?:^|-)hans(?:-|$)/.test(tag)) return 'zh-Hans';
    if (/(?:^|-)(cn|sg)(?:-|$)/.test(tag)) return 'zh-Hans';
    if (/(?:^|-)(tw|hk|mo)(?:-|$)/.test(tag)) return 'zh-Hant';
    return 'zh-Hans';
  }
  const primary = tag.split('-')[0];
  return (['en', 'ja', 'ko', 'es', 'fr', 'ru'] as const).find((language) => language === primary) || 'en';
}
export const botLanguageNames: Record<BotLanguage, string> = {
  'zh-Hant': '繁體中文', 'zh-Hans': '简体中文', en: 'English', ja: '日本語', ko: '한국어',
  es: 'Español', fr: 'Français', ru: 'Русский',
};
// Translate the static template before inserting music metadata. UI language
// must never translate or normalize a song, artist, album, URL or filename.
const catalog = {
  single: ["單曲", "Songs", "曲", "곡", "Canciones", "Titres", "Песни"],
  artist: ["藝術家", "Artists", "アーティスト", "아티스트", "Artistas", "Artistes", "Исполнители"],
  hotTracks: ["熱門單曲", "Top songs", "人気の曲", "인기곡", "Canciones populares", "Titres populaires", "Популярные песни"],
  backResults: ["返回", "Back", "戻る", "뒤로", "Volver", "Retour", "Назад"],
  close: ["關閉", "Close", "閉じる", "닫기", "Cerrar", "Fermer", "Закрыть"],
  chooseNumber: ["點序號選擇", "Choose a number", "番号を選択", "번호 선택", "Elige un número", "Choisissez un numéro", "Выберите номер"],
  chooseNumberGroup: ["點序號，或回覆列表輸入序號", "Choose a number, or reply to this list with its number", "番号を選ぶか、一覧に番号で返信", "번호 선택 또는 목록에 번호로 답장", "Elige un número o responde a esta lista con el número", "Choisissez un numéro ou répondez à cette liste avec le numéro", "Выберите номер или ответьте на список номером"],
  resultsLimit: ["載入 {loaded} / {total} 個結果", "Loaded {loaded} / {total} results", "{total} 件中 {loaded} 件を表示", "{total}개 중 {loaded}개 표시", "{loaded} / {total} resultados", "{loaded} / {total} résultats", "{loaded} / {total} результатов"],
  tracksCount: ["{count} 首", "{count} songs", "{count} 曲", "{count}곡", "{count} canciones", "{count} titres", "{count} песен"],
  noResults: ["沒有符合的結果，試試其他分類或關鍵字。", "No matches. Try another category or keyword.", "見つかりません。種類やキーワードを変えてください。", "결과가 없습니다. 다른 분류나 검색어를 선택하세요.", "Sin resultados. Prueba otra categoría o palabra.", "Aucun résultat. Essayez une autre catégorie ou recherche.", "Нет результатов. Выберите другую категорию или запрос."],
  cmdAlbum: ["搜尋專輯", "Search albums", "アルバムを検索", "앨범 검색", "Buscar álbumes", "Chercher des albums", "Поиск альбомов"],
  cmdArtist: ["搜尋藝術家", "Search artists", "アーティストを検索", "아티스트 검색", "Buscar artistas", "Chercher des artistes", "Поиск исполнителей"],
  cmdPlaylist: ["搜尋歌單", "Search playlists", "プレイリストを検索", "재생목록 검색", "Buscar listas", "Chercher des playlists", "Поиск плейлистов"],

  changeLanguage: ["切換語言", "Switch language", "言語を変更", "언어 변경", "Cambiar idioma", "Changer de langue", "Изменить язык"],
  settings: ["Bot 設定", "Bot settings", "Bot の設定", "봇 설정", "Ajustes del bot", "Paramètres du bot", "Настройки бота"],
  uiLanguage: ["Bot 介面語言", "Bot interface language", "Bot の表示言語", "봇 인터페이스 언어", "Idioma del bot", "Langue du bot", "Язык бота"],
  namesSetting: ["網易雲中文名稱字形", "NetEase Chinese names", "NetEase の中国語表記", "NetEase 중국어 표기", "Nombres chinos de NetEase", "Noms chinois de NetEase", "Китайские названия NetEase"],
  scope: ["介面語言只影響 Bot 提示與按鈕。中文名稱字形只適用網易雲。", "Interface language changes bot messages and buttons. Chinese name settings apply only to NetEase.", "表示言語は Bot のメッセージとボタンに適用されます。中国語表記の設定は NetEase 専用です。", "인터페이스 언어는 봇 메시지와 버튼에만 적용됩니다. 중국어 표기 설정은 NetEase 전용입니다.", "El idioma cambia los mensajes y botones del bot. Los nombres chinos se ajustan solo en NetEase.", "La langue concerne les messages et boutons du bot. Le réglage des noms chinois est réservé à NetEase.", "Язык применяется к сообщениям и кнопкам бота. Настройка китайских названий действует только для NetEase."],
  current: ["目前：{value}", "Current: {value}", "現在：{value}", "현재: {value}", "Actual: {value}", "Actuel : {value}", "Сейчас: {value}"],
  unset: ["尚未設定", "Not set", "未設定", "미설정", "Sin configurar", "Non défini", "Не задано"],
  original: ["Original（中文保留原樣）", "Original Chinese spelling", "中国語表記をそのまま保持", "중국어 원문 유지", "Chino original", "Chinois d’origine", "Исходное китайское написание"],
  traditional: ["中文統一繁體（TC）", "Traditional Chinese (TC)", "中国語を繁体字に統一（TC）", "중국어 번체 통일 (TC)", "Chino tradicional (TC)", "Chinois traditionnel (TC)", "Традиционные иероглифы (TC)"],
  simplified: ["中文统一简体（SC）", "Simplified Chinese (SC)", "中国語を簡体字に統一（SC）", "중국어 간체 통일 (SC)", "Chino simplificado (SC)", "Chinois simplifié (SC)", "Упрощённые иероглифы (SC)"],
  firstNames: ["首次獲取網易雲歌曲：請選擇中文名稱字形。選完會自動繼續剛才的歌曲。", "Your first NetEase download: choose Chinese spelling. Your song will continue automatically.", "初めての NetEase ダウンロード：中国語表記を選んでください。選択後、曲の取得を再開します。", "첫 NetEase 다운로드: 중국어 표기를 선택하세요. 선택하면 다운로드가 자동으로 계속됩니다.", "Primera descarga de NetEase: elige la escritura china. La descarga continuará automáticamente.", "Premier téléchargement NetEase : choisissez l’écriture chinoise. Le téléchargement reprendra automatiquement.", "Первая загрузка NetEase: выберите китайское написание. Загрузка продолжится автоматически."],
  namesScope: ["僅統一網易雲中文歌名、歌手名與專輯名的繁簡字形；其他語言保留原文。Spotify、YTM 名稱保留來源原文。", "Normalize only Chinese song, artist and album names from NetEase. Other languages and all Spotify/YTM names keep their source spelling.", "NetEase の中国語の曲名・アーティスト名・アルバム名のみを統一します。他の言語と Spotify・YTM の名前は元の表記を保持します。", "NetEase의 중국어 곡명·아티스트명·앨범명만 통일합니다. 다른 언어와 Spotify·YTM 이름은 원문을 유지합니다.", "Solo se ajustan los títulos, artistas y álbumes chinos de NetEase. Otros idiomas y los nombres de Spotify/YTM conservan el original.", "Seuls les titres, artistes et albums chinois de NetEase sont ajustés. Les autres langues et les noms Spotify/YTM restent inchangés.", "Меняется только китайское написание песен, исполнителей и альбомов NetEase. Другие языки и названия Spotify/YTM сохраняются."],
  uiScope: ["選擇 Bot 提示與按鈕的語言。歌曲、歌手與專輯名稱不受影響。", "Choose the language of bot messages and buttons. Song, artist and album names stay unchanged.", "Bot のメッセージとボタンの言語を選んでください。曲名・アーティスト名・アルバム名は変わりません。", "봇 메시지와 버튼의 언어를 선택하세요. 곡명·아티스트명·앨범명은 바뀌지 않습니다.", "Elige el idioma de los mensajes y botones. Los títulos, artistas y álbumes no cambian.", "Choisissez la langue des messages et boutons. Les titres, artistes et albums ne changent pas.", "Выберите язык сообщений и кнопок. Названия песен, исполнителей и альбомов не изменятся."],
  uiSaved: ["Bot 介面語言已設定為 {value}。", "Bot interface language set to {value}.", "Bot の表示言語を {value} に設定しました。", "봇 인터페이스 언어를 {value}(으)로 설정했습니다.", "Idioma del bot: {value}.", "Langue du bot : {value}.", "Язык бота изменён на {value}."],
  namesSaved: ["網易雲中文名稱字形已設定為 {value}。", "NetEase Chinese spelling set to {value}.", "NetEase の中国語表記を {value} に設定しました。", "NetEase 중국어 표기를 {value}(으)로 설정했습니다.", "Escritura china de NetEase: {value}.", "Écriture chinoise de NetEase : {value}.", "Китайское написание NetEase: {value}."],
  back: ["返回設定", "Back to settings", "設定に戻る", "설정으로 돌아가기", "Volver a ajustes", "Retour aux paramètres", "Назад к настройкам"],
  wrongOwner: ["這是其他用戶的設定按鈕，請使用 /settings 開啟自己的設定。", "These settings belong to another user. Open yours with /settings.", "他のユーザーの設定です。/settings で自分の設定を開いてください。", "다른 사용자의 설정입니다. /settings로 본인 설정을 여세요.", "Estos ajustes son de otro usuario. Abre los tuyos con /settings.", "Ces paramètres appartiennent à un autre utilisateur. Ouvrez les vôtres avec /settings.", "Это настройки другого пользователя. Откройте свои командой /settings."],
  fetching: ["正在獲取「{title}」的 {source} 原始音源…", "Fetching the original {source} audio for “{title}”…", "「{title}」の {source} オリジナル音源を取得中…", "“{title}”의 {source} 원본 음원을 가져오는 중…", "Obteniendo el audio original de {source} para «{title}»…", "Récupération de l’audio original {source} pour « {title} »…", "Загрузка исходного аудио {source} для «{title}»…"],
  tooLarge: ["音訊超過 Telegram 49 MB 發送限制，請使用網頁端獲取。", "Audio exceeds the 49 MB Telegram limit. Use the website to download it.", "Telegram の 49 MB 上限を超えています。ウェブサイトから取得してください。", "Telegram의 49 MB 한도를 초과했습니다. 웹사이트에서 다운로드하세요.", "El audio supera el límite de 49 MB de Telegram. Descárgalo en la web.", "L’audio dépasse la limite Telegram de 49 Mo. Téléchargez-le sur le site.", "Аудио превышает лимит Telegram в 49 МБ. Загрузите его через сайт."],
  documentFallback: ["Telegram 未接受此格式為音樂卡片，已保留原始音訊以檔案發送。", "Telegram could not display this format as music. The original audio was sent as a file.", "Telegram がこの形式を音楽として表示できないため、元の音声をファイルで送信しました。", "Telegram이 이 형식을 음악으로 표시하지 못해 원본 음원을 파일로 보냈습니다.", "Telegram no pudo mostrar este formato como música. Se envió el audio original como archivo.", "Telegram ne peut pas afficher ce format comme musique. L’audio original a été envoyé comme fichier.", "Telegram не смог показать этот формат как музыку. Исходное аудио отправлено файлом."],
  pending: ["任務仍在佇列中，請稍後重試或使用網頁端。", "The task is still queued. Try again later or use the website.", "処理は待機中です。後でもう一度試すか、ウェブサイトをご利用ください。", "작업이 아직 대기 중입니다. 나중에 다시 시도하거나 웹사이트를 이용하세요.", "La tarea sigue en cola. Inténtalo más tarde o usa la web.", "La tâche est toujours en attente. Réessayez plus tard ou utilisez le site.", "Задача ещё в очереди. Повторите позже или используйте сайт."],
  notFound: ["沒有找到歌曲，請試試其他關鍵字。", "No songs found. Try other keywords.", "曲が見つかりません。別のキーワードを試してください。", "곡을 찾지 못했습니다. 다른 검색어를 사용하세요.", "No se encontraron canciones. Prueba otras palabras.", "Aucune chanson trouvée. Essayez d’autres mots-clés.", "Песни не найдены. Попробуйте другие слова."],
  selectTracks: ["{kind} · {source}\n{start}–{end} / {loaded}\n點選曲目，或發送序號。", "{kind} · {source}\n{start}–{end} / {loaded}\nChoose a song or send its number.", "{kind} · {source}\n{start}–{end} / {loaded}\n曲を選ぶか、番号を送信してください。", "{kind} · {source}\n{start}–{end} / {loaded}\n곡을 선택하거나 번호를 보내세요.", "{kind} · {source}\n{start}–{end} / {loaded}\nElige una canción o envía su número.", "{kind} · {source}\n{start}–{end} / {loaded}\nChoisissez un titre ou envoyez son numéro.", "{kind} · {source}\n{start}–{end} / {loaded}\nВыберите песню или отправьте её номер."],
  selectTracksGroup: ["{kind} · {source}\n{start}–{end} / {loaded}\n點選曲目，或回覆這則列表並輸入序號。", "{kind} · {source}\n{start}–{end} / {loaded}\nChoose a song, or reply to this list with its number.", "{kind} · {source}\n{start}–{end} / {loaded}\n曲を選ぶか、このリストに番号で返信してください。", "{kind} · {source}\n{start}–{end} / {loaded}\n곡을 선택하거나 이 목록에 번호로 답장하세요.", "{kind} · {source}\n{start}–{end} / {loaded}\nElige una canción o responde a esta lista con su número.", "{kind} · {source}\n{start}–{end} / {loaded}\nChoisissez un titre ou répondez à cette liste avec son numéro.", "{kind} · {source}\n{start}–{end} / {loaded}\nВыберите песню или ответьте на этот список её номером."],
  songs: ["歌曲", "Songs", "曲", "곡", "Canciones", "Titres", "Песни"],
  playlist: ["歌單", "Playlist", "プレイリスト", "재생목록", "Lista", "Playlist", "Плейлист"],
  collectionLimit: ["共 {total} 首，本次載入 {loaded} 首。", "{total} songs in total; {loaded} loaded.", "全 {total} 曲のうち {loaded} 曲を読み込みました。", "총 {total}곡 중 {loaded}곡을 불러왔습니다.", "{total} canciones en total; {loaded} cargadas.", "{total} titres au total ; {loaded} chargés.", "Всего {total} песен; загружено {loaded}."],
  previousPage: ["上一頁", "Previous", "前へ", "이전", "Anterior", "Précédent", "Назад"],
  nextPage: ["下一頁", "Next", "次へ", "다음", "Siguiente", "Suivant", "Далее"],
  selectionExpired: ["選曲列表已過期，請重新發送關鍵字或連結。", "This selection expired. Send the keywords or link again.", "選曲リストの期限が切れました。キーワードかリンクを再送信してください。", "선택 목록이 만료되었습니다. 검색어나 링크를 다시 보내세요.", "La selección caducó. Envía de nuevo las palabras o el enlace.", "Cette sélection a expiré. Renvoyez les mots-clés ou le lien.", "Список устарел. Отправьте запрос или ссылку снова."],
  selectionOwner: ["這是其他用戶的選曲列表，請自己發送關鍵字或連結。", "This selection belongs to another user. Send your own keywords or link.", "他のユーザーのリストです。自分のキーワードかリンクを送信してください。", "다른 사용자의 목록입니다. 검색어나 링크를 직접 보내세요.", "Esta selección pertenece a otra persona. Envía tu propia búsqueda o enlace.", "Cette sélection appartient à un autre utilisateur. Envoyez votre recherche ou lien.", "Этот список другого пользователя. Отправьте свой запрос или ссылку."],
  selectionNumber: ["請使用目前列表中的曲目序號。歌曲 ID 請用 /netease ID。", "Use a song number from the current list. For a song ID, use /netease ID.", "現在のリストの曲番号を使ってください。曲 ID は /netease ID で指定します。", "현재 목록의 곡 번호를 사용하세요. 곡 ID는 /netease ID로 지정하세요.", "Usa un número de la lista actual. Para un ID usa /netease ID.", "Utilisez un numéro de la liste actuelle. Pour un ID : /netease ID.", "Укажите номер из списка. Для ID песни используйте /netease ID."],
  rateLimited: ["請稍候幾秒再發送下一個請求。", "Wait a few seconds before your next request.", "次のリクエストまで数秒お待ちください。", "다음 요청까지 잠시 기다려 주세요.", "Espera unos segundos antes de otra solicitud.", "Attendez quelques secondes avant la prochaine demande.", "Подождите несколько секунд перед следующим запросом."],
  browseIntro: ["發送歌名、藝術家名稱或連結；搜尋結果可切換單曲、專輯、藝術家與歌單。", "Send a song, artist name or link. Switch between songs, albums, artists and playlists in the results.", "曲名・アーティスト名・リンクを送信。結果で曲・アルバム・アーティスト・プレイリストを切り替えられます。", "곡명, 아티스트 이름 또는 링크를 보내세요. 결과에서 곡·앨범·아티스트·재생목록을 선택하세요.", "Envía una canción, artista o enlace. Cambia entre canciones, álbumes, artistas y listas en los resultados.", "Envoyez un titre, un artiste ou un lien. Les résultats proposent titres, albums, artistes et playlists.", "Отправьте название песни, исполнителя или ссылку. В результатах можно выбрать песни, альбомы, исполнителей или плейлисты."],
  helpIntro: ["直接發送歌名、歌手名或音樂連結。搜尋結果可點選或發送序號。", "Send a song name, artist name or music link. Choose a result or send its number.", "曲名・アーティスト名・音楽リンクを送信してください。結果を選ぶか、番号を送信できます。", "곡명·아티스트명·음악 링크를 보내세요. 검색 결과를 선택하거나 번호를 보낼 수 있습니다.", "Envía un título, artista o enlace musical. Elige un resultado o envía su número.", "Envoyez un titre, un artiste ou un lien musical. Choisissez un résultat ou envoyez son numéro.", "Отправьте название песни, исполнителя или ссылку. Выберите результат или отправьте его номер."],
  helpGroup: ["群組請使用 /search@{botUsername} 關鍵字，或回覆 Bot 搜尋。點選結果，或回覆列表並輸入序號。", "In groups, use /search@{botUsername} keywords or reply to the bot to search. Choose a result, or reply to its list with a number.", "グループでは /search@{botUsername} キーワード、または Bot への返信で検索できます。結果を選ぶか、リストに番号で返信してください。", "그룹에서는 /search@{botUsername} 검색어 또는 봇에 답장하여 검색하세요. 결과를 선택하거나 목록에 번호로 답장하세요.", "En grupos, usa /search@{botUsername} palabras o responde al bot para buscar. Elige un resultado o responde a la lista con un número.", "En groupe, utilisez /search@{botUsername} mots-clés ou répondez au bot. Choisissez un résultat ou répondez à la liste avec un numéro.", "В группе используйте /search@{botUsername} запрос или ответьте боту. Выберите результат или ответьте на список номером."],
  cmdNetease: ["網易雲歌名、ID 或連結；關鍵字取第一首", "NetEase name, ID or link; first keyword result", "NetEase の曲名・ID・リンク（検索は最初の曲）", "NetEase 곡명·ID·링크 (검색 첫 번째 곡)", "NetEase: nombre, ID o enlace; primer resultado", "NetEase : titre, ID ou lien ; premier résultat", "NetEase: название, ID или ссылка; первый результат"],
  cmdSearch: ["搜尋網易雲：單曲、專輯、藝術家、歌單", "Search NetEase: songs, albums, artists, playlists", "NetEase の曲・アルバム・アーティスト・プレイリストを検索", "NetEase 곡·앨범·아티스트·재생목록 검색", "Buscar en NetEase: canciones, álbumes, artistas y listas", "Chercher sur NetEase : titres, albums, artistes, playlists", "Поиск NetEase: песни, альбомы, исполнители, плейлисты"],
  cmdSpotify: ["搜尋 Spotify", "Search Spotify", "Spotify を検索", "Spotify 검색", "Buscar en Spotify", "Chercher sur Spotify", "Поиск Spotify"],
  cmdYtm: ["獲取 YouTube Music 連結", "Download a YouTube Music link", "YouTube Music のリンクから取得", "YouTube Music 링크 다운로드", "Descargar enlace de YouTube Music", "Télécharger un lien YouTube Music", "Загрузить по ссылке YouTube Music"],
  cmdDownload: ["解析音樂連結並獲取", "Resolve and download a music link", "音楽リンクを解析して取得", "음악 링크 분석 및 다운로드", "Analizar y descargar enlace musical", "Analyser et télécharger un lien musical", "Разобрать и загрузить музыкальную ссылку"],
  cmdLyric: ["網易雲歌名、ID 或連結；獲取 LRC 歌詞", "NetEase name, ID or link; get LRC lyrics", "NetEase の曲名・ID・リンクから LRC 歌詞を取得", "NetEase 곡명·ID·링크로 LRC 가사 받기", "NetEase: nombre, ID o enlace; letra LRC", "NetEase : titre, ID ou lien ; paroles LRC", "NetEase: название, ID или ссылка; текст LRC"],
  cmdSettings: ["Bot 介面語言與網易雲中文名稱字形", "Bot language and NetEase Chinese names", "Bot の言語と NetEase の中国語表記", "봇 언어 및 NetEase 중국어 표기", "Idioma del bot y nombres chinos de NetEase", "Langue du bot et noms chinois de NetEase", "Язык бота и китайские названия NetEase"],
  cmdAbout: ["關於音樂主義", "About ismusicnow", "ismusicnow について", "ismusicnow 소개", "Acerca de ismusicnow", "À propos d’ismusicnow", "Об ismusicnow"],
  firstNotice: ["首次獲取網易雲歌曲會先選中文名稱字形，之後沿用你的偏好。", "Your first NetEase download asks for Chinese spelling, then remembers your choice.", "初回の NetEase ダウンロードで中国語表記を選択し、次回から保存した設定を使います。", "첫 NetEase 다운로드에서 중국어 표기를 선택하면 다음부터 기억합니다.", "La primera descarga de NetEase pide la escritura china y recuerda tu elección.", "Le premier téléchargement NetEase demande l’écriture chinoise et mémorise votre choix.", "При первой загрузке NetEase выберите китайское написание. Выбор будет сохранён."],
  sourceNote: ["Spotify 使用 Spotify 原始音源；YTM 使用獨立適配器。", "Spotify uses its original audio; YTM has its own adapter.", "Spotify は元の Spotify 音源を使用し、YTM は専用の取得機能を使用します。", "Spotify는 원본 음원을 사용하며 YTM은 별도 어댑터를 사용합니다.", "Spotify usa su audio original; YTM tiene su propio adaptador.", "Spotify utilise son audio original ; YTM possède son propre adaptateur.", "Spotify использует своё исходное аудио; YTM — отдельный адаптер."],
  license: ["開源授權 GPL-3.0，不附帶擔保。", "Open source under GPL-3.0, without warranty.", "GPL-3.0 のオープンソースです。無保証です。", "GPL-3.0 오픈 소스이며 보증은 제공하지 않습니다.", "Código abierto GPL-3.0, sin garantía.", "Logiciel libre GPL-3.0, sans garantie.", "Открытый код GPL-3.0, без гарантий."],
  lyricInput: ["請輸入 /lyric 網易雲歌名、歌曲 ID 或連結。", "Use /lyric followed by a NetEase song name, ID or link.", "/lyric の後に NetEase の曲名・ID・リンクを入力してください。", "/lyric 뒤에 NetEase 곡명·ID·링크를 입력하세요.", "Usa /lyric con nombre, ID o enlace de NetEase.", "Utilisez /lyric avec un titre, ID ou lien NetEase.", "После /lyric укажите название, ID или ссылку NetEase."],
  noLyric: ["這首歌暫時沒有 LRC 歌詞。", "LRC lyrics are not available for this song.", "この曲の LRC 歌詞はありません。", "이 곡의 LRC 가사가 없습니다.", "No hay letra LRC para esta canción.", "Les paroles LRC sont indisponibles pour ce titre.", "Для этой песни нет текста LRC."],
  queryInput: ["請在命令後輸入關鍵字或音樂連結。", "Add keywords or a music link after the command.", "コマンドの後にキーワードか音楽リンクを入力してください。", "명령어 뒤에 검색어나 음악 링크를 입력하세요.", "Añade palabras clave o un enlace tras el comando.", "Ajoutez des mots-clés ou un lien après la commande.", "После команды укажите поисковые слова или музыкальную ссылку."],
  album: ["專輯", "Album", "アルバム", "앨범", "Álbum", "Album", "Альбом"],
  source: ["來源", "Source", "配信元", "출처", "Fuente", "Source", "Источник"],
  unknownArtist: ["未知歌手", "Unknown artist", "不明なアーティスト", "알 수 없는 아티스트", "Artista desconocido", "Artiste inconnu", "Неизвестный исполнитель"],
  unknownAlbum: ["未提供專輯名稱", "Album not provided", "アルバム名なし", "앨범 정보 없음", "Álbum no indicado", "Album non renseigné", "Альбом не указан"],
  originalAudio: ["原始音源", "Original audio", "オリジナル音源", "원본 음원", "Audio original", "Audio original", "Исходное аудио"],
  openSource: ["在來源平台開啟", "Open on source platform", "配信元で開く", "원본 플랫폼에서 열기", "Abrir en la plataforma", "Ouvrir sur la plateforme", "Открыть на платформе"],
  spotifyCookies: ["Spotify 登入尚未配置或已無法讀取，請聯絡管理員補上 cookies 登入檔。", "Spotify login is not configured or readable. Ask the administrator to add the cookies file.", "Spotify のログイン設定がないか読み取れません。管理者に cookies ファイルの設定を依頼してください。", "Spotify 로그인 설정이 없거나 읽을 수 없습니다. 관리자에게 cookies 파일 설정을 요청하세요.", "El inicio de sesión de Spotify no está configurado o no se puede leer. Pide al administrador el archivo de cookies.", "La connexion Spotify est absente ou illisible. Demandez à l’administrateur de configurer le fichier cookies.", "Вход Spotify не настроен или недоступен. Попросите администратора добавить файл cookies."],
  spotifySetup: ["Spotify 搜尋需要服務端 API 設定，請聯絡管理員；也可直接貼單曲連結。", "Spotify search needs server API credentials. Contact the administrator or paste a track link.", "Spotify 検索には API 設定が必要です。管理者に連絡するか、曲のリンクを貼ってください。", "Spotify 검색에는 서버 API 설정이 필요합니다. 관리자에게 문의하거나 곡 링크를 보내세요.", "La búsqueda de Spotify necesita credenciales API. Contacta al administrador o pega un enlace de canción.", "La recherche Spotify nécessite une configuration API. Contactez l’administrateur ou collez un lien de titre.", "Для поиска Spotify нужны API-данные. Обратитесь к администратору или отправьте ссылку на песню."],
  unavailableAudio: ["平台未提供可下載的完整音源，請確認帳號、地區或曲目權限。", "The platform did not provide a complete downloadable track. Check account, region and track access.", "完全な音源を取得できません。アカウント・地域・曲の利用権限を確認してください。", "전체 음원을 받을 수 없습니다. 계정·지역·곡 이용 권한을 확인하세요.", "No hay una pista completa disponible. Revisa la cuenta, región y permisos.", "Aucun audio complet disponible. Vérifiez le compte, la région et les droits d’accès.", "Полное аудио недоступно. Проверьте аккаунт, регион и права доступа."],
  adapterFailed: ["下載適配器無法完成任務，請檢查登入、訂閱權限與服務端設定。", "The download adapter could not finish. Check login, subscription and server settings.", "取得処理に失敗しました。ログイン・サブスクリプション・サーバー設定を確認してください。", "다운로드를 완료하지 못했습니다. 로그인·구독·서버 설정을 확인하세요.", "No se pudo completar la descarga. Revisa el inicio de sesión, suscripción y configuración.", "Le téléchargement a échoué. Vérifiez la connexion, l’abonnement et la configuration.", "Загрузка не завершена. Проверьте вход, подписку и настройки сервера."],
  serviceError: ["音樂服務暫時無法回應，請稍後再試。", "The music service is unavailable. Try again later.", "音楽サービスに接続できません。後でもう一度試してください。", "음악 서비스에 연결할 수 없습니다. 나중에 다시 시도하세요.", "El servicio de música no responde. Inténtalo más tarde.", "Le service musical est indisponible. Réessayez plus tard.", "Музыкальный сервис недоступен. Повторите позже."],
  wrongProvider: ["此命令用於網易雲；其他平台請直接貼連結或使用對應命令。", "This command is for NetEase. For other platforms, paste a link or use their command.", "このコマンドは NetEase 専用です。他のサービスはリンクか専用コマンドを使ってください。", "이 명령어는 NetEase 전용입니다. 다른 플랫폼은 링크나 해당 명령어를 사용하세요.", "Este comando es para NetEase. Usa un enlace o el comando de la otra plataforma.", "Cette commande est réservée à NetEase. Utilisez un lien ou la commande de l’autre plateforme.", "Эта команда для NetEase. Для других платформ отправьте ссылку или используйте их команду."],
  invalidLink: ["請提供網易雲、Spotify 或 YouTube Music 的完整歌曲、專輯或歌單連結。", "Use a full song, album or playlist link from NetEase, Spotify or YouTube Music.", "NetEase、Spotify、YouTube Music の完全な曲・アルバム・プレイリストのリンクを入力してください。", "NetEase, Spotify 또는 YouTube Music의 전체 곡·앨범·재생목록 링크를 입력하세요.", "Usa un enlace completo de canción, álbum o lista de NetEase, Spotify o YouTube Music.", "Utilisez un lien complet de titre, album ou playlist NetEase, Spotify ou YouTube Music.", "Укажите полную ссылку на песню, альбом или плейлист NetEase, Spotify или YouTube Music."],
  queueFull: ["下載佇列已滿，請稍後再試。", "The download queue is full. Try again later.", "取得待ちの上限に達しました。後でもう一度試してください。", "다운로드 대기열이 가득 찼습니다. 나중에 다시 시도하세요.", "La cola está llena. Inténtalo más tarde.", "La file d’attente est pleine. Réessayez plus tard.", "Очередь заполнена. Повторите позже."],
  timeout: ["處理超時，請稍後重試或使用網頁端。", "The request timed out. Try again later or use the website.", "処理がタイムアウトしました。後で試すか、ウェブサイトをご利用ください。", "요청 시간이 초과되었습니다. 나중에 다시 시도하거나 웹사이트를 이용하세요.", "La solicitud tardó demasiado. Inténtalo más tarde o usa la web.", "Le délai a expiré. Réessayez plus tard ou utilisez le site.", "Время ожидания истекло. Повторите позже или используйте сайт."],
  unavailableFile: ["檔案已過期或尚未完成，請重新獲取歌曲。", "The file has expired or is not ready. Request the song again.", "ファイルが期限切れか未完成です。曲を再取得してください。", "파일이 만료되었거나 준비되지 않았습니다. 곡을 다시 요청하세요.", "El archivo caducó o no está listo. Solicita la canción otra vez.", "Le fichier a expiré ou n’est pas prêt. Demandez à nouveau le titre.", "Файл истёк или ещё не готов. Запросите песню снова."],
  restarted: ["服務已重啟，請重新獲取歌曲。", "The service restarted. Request the song again.", "サービスが再起動しました。曲を再取得してください。", "서비스가 재시작되었습니다. 곡을 다시 요청하세요.", "El servicio se reinició. Solicita la canción otra vez.", "Le service a redémarré. Demandez à nouveau le titre.", "Сервис перезапущен. Запросите песню снова."],
} satisfies Record<string, readonly [string, string, string, string, string, string, string]>;
export type BotTextKey = keyof typeof catalog;
const columns = { 'zh-Hant': 0, 'zh-Hans': 0, en: 1, ja: 2, ko: 3, es: 4, fr: 5, ru: 6 } as const;
const toSimplified = Converter({ from: 'tw', to: 'cn' });
export function botText(language: BotLanguage, key: BotTextKey, values: Record<string, string | number> = {}): string {
  const template = catalog[key][columns[language]];
  const translated = language === 'zh-Hans' ? toSimplified(template) : template;
  return translated.replace(/\{(\w+)\}/g, (match, name: string) => Object.hasOwn(values, name) ? String(values[name]) : match);
}
const errors: Record<string, BotTextKey> = {
  SELECTION_EXPIRED: 'selectionExpired', SELECTION_OWNER: 'selectionOwner', SELECTION_NUMBER: 'selectionNumber',
  SPOTIFY_COOKIES: 'spotifyCookies', SPOTIFY_SETUP: 'spotifySetup', NOT_FOUND: 'notFound', WRONG_PROVIDER: 'wrongProvider',
  NO_AUDIO: 'unavailableAudio', PREVIEW_ONLY: 'unavailableAudio', INCOMPLETE_AUDIO: 'unavailableAudio', LOSSLESS_UNAVAILABLE: 'unavailableAudio',
  ADAPTER_FAILED: 'adapterFailed', NO_OUTPUT: 'adapterFailed', TOOL_MISSING: 'adapterFailed', INVALID_QUALITY: 'adapterFailed',
  DOWNLOAD_TIMEOUT: 'timeout', FILE_TOO_LARGE: 'tooLarge', QUEUE_FULL: 'queueFull',
  INVALID_INPUT: 'queryInput', INVALID_URL: 'invalidLink', UNSUPPORTED_LINK: 'invalidLink', UNSUPPORTED_HOST: 'invalidLink',
  SHORT_LINK: 'invalidLink', INVALID_TRACK: 'invalidLink', YTM_LINK_REQUIRED: 'invalidLink',
  EXPIRED: 'unavailableFile', NOT_READY: 'unavailableFile', SERVICE_RESTARTED: 'restarted',
  BATCH_LIMIT: 'queryInput', ORIGINAL_ONLY: 'adapterFailed', NOT_LOSSLESS: 'unavailableAudio',
};
export const botError = (language: BotLanguage, code?: string) => botText(language, errors[code || ''] || 'serviceError');
export function botCommands(language: BotLanguage) {
  return ([['netease', 'cmdNetease'], ['music', 'cmdNetease'], ['search', 'cmdSearch'], ['spotify', 'cmdSpotify'],
    ['ytm', 'cmdYtm'], ['album', 'cmdAlbum'], ['artist', 'cmdArtist'], ['playlist', 'cmdPlaylist'], ['download', 'cmdDownload'], ['lyric', 'cmdLyric'], ['settings', 'cmdSettings'], ['about', 'cmdAbout']] as const)
    .map(([command, key]) => ({ command, description: botText(language, key).slice(0, 256) }));
}
export function botHelp(language: BotLanguage, group = false, botUsername = 'muismbot'): string {
  return ['ismusicnow · 音樂主義', '', botText(language, group ? 'helpGroup' : 'browseIntro', { botUsername }),
    ...botCommands(language).filter(c => ['search', 'netease', 'spotify', 'ytm', 'settings'].includes(c.command)).map((c) => `/${c.command} — ${c.description}`)].join('\n');
}
